sudo: required

language: python

services:
  - docker

# authenticate docker hub and pull image from repo
before_install:
- docker login -e DCS_PaaS@dell.com -u dcspaas -p PaaSword@123
- docker pull dcspaas/webapp:python

# setup python requirements and dependencies
install:
- pip install -r webapp/requirements.txt


# create container, update code from repo, and start it
before_script:
- WORKING_DIR=$(pwd)
- docker create -P dcspaas/webapp:python python app.py
- CONTAINER_ID=$(docker ps -lq)
- docker cp webapp $CONTAINER_ID:/opt/
- docker start $CONTAINER_ID

# run unit tests (need to run this externally and internally)
script:
- python webapp/tests.py
- docker exec $CONTAINER_ID python tests.py

after_success:
- docker commit $CONTAINER_ID dcspaas/webapp:python
- docker push dcspaas/webapp:python