sudo: required

language: python

services:
  - docker

before_install:
- docker login -e DCS_PaaS@dell.com -u dcspaas -p PaaSword@123
- docker pull dcspaas/webapp:python

install:
- pip install -r webapp/requirements.txt

before_script:
- WORKING_DIR=$(pwd)
- docker create -v $WORKING_DIR/webapp:/opt/webapp -P dcspaas/webapp:python python app.py
- CONTAINER_ID=$(docker ps -lq) 
- docker start $CONTAINER_ID

script:
- python webapp/tests.py

after_success:
- docker commit $CONTAINER_ID dcspaas/webapp:python
- docker push dcspaas/webapp:python
